#include "windows.h"

struct ArticleBuffer
{ // see 
    TCHAR* title;
    int image;
    void* doc;
    const char* init_doc;

    int scrollPosition;
    int scrollOffset;
    int selAnchor;
    int selPosition;
    CControlUI* testFrame;
};

ArticleBuffer demoArticles[]
{
    {L"happy", 0, 0, "adj.感到（或显得）快乐的；高兴的；给予（或带来）快乐的；使人高兴的\n"
    "幸福的；开心；欢乐。\n"
    "幸福的；开心；欢乐。\n"
    "幸福的；开心；欢乐。\n"
    "幸福的；开心；欢乐。\n"
    "幸福的；开心；欢乐。\n"
    "幸福的；开心；欢乐。\n"
    "幸福的；开心；欢乐。\n"
    "幸福的；开心；欢乐。\n"
    "幸福的；开心；欢乐。\n"
    "幸福的；开心；欢乐。\n"
    "幸福的；开心；欢乐。\n"
    "幸福的；开心；欢乐。\n"
    "幸福的；开心；欢乐。\n"
    "幸福的；开心；欢乐。\n"
    "幸福的；开心；欢乐。\n"
    "幸福的；开心；欢乐。\n"
    "幸福的；开心；欢乐。\n"
    "幸福的；开心；欢乐。\n"
    "幸福的；开心；欢乐。\n"
    "幸福的；开心；欢乐。\n"
    "幸福的；开心；欢乐。\n"
    "幸福的；开心；欢乐。\n"
    "幸福的；开心；欢乐。\n"
    "幸福的；开心；欢乐。\n"
    "幸福的；开心；欢乐。\n"
    "幸福的；开心；欢乐。\n"
    "幸福的；开心；欢乐。\n"
    "幸福的；开心；欢乐。\n"
    "幸福的；开心；欢乐。\n"
    "幸福的；开心；欢乐。\n"
    "幸福的；开心；欢乐。\n"
    "幸福的；开心；欢乐。\n"
    }
    ,{L"happy for what", 1, 0, "happy for you"}
    ,{L"< 测试按钮控件 >", 1, 0, "-"}
    ,{L"sad", 0, 0, "adj.悲哀的；难过的；显得悲哀的；令人悲哀的\n"
    "悲伤的；伤心；忧愁的。\n"
    "悲伤的；伤心；忧愁的。\n"
    "悲伤的；伤心；忧愁的。\n"
    "悲伤的；伤心；忧愁的。\n"
    "悲伤的；伤心；忧愁的。\n"
    "悲伤的；伤心；忧愁的。\n"
    "悲伤的；伤心；忧愁的。\n"
    "悲伤的；伤心；忧愁的。\n"
    "悲伤的；伤心；忧愁的。\n"
    "悲伤的；伤心；忧愁的。\n"
    "悲伤的；伤心；忧愁的。\n"
    "悲伤的；伤心；忧愁的。\n"
    "悲伤的；伤心；忧愁的。\n"
    "悲伤的；伤心；忧愁的。\n"
    "悲伤的；伤心；忧愁的。\n"
    "悲伤的；伤心；忧愁的。\n"
    "悲伤的；伤心；忧愁的。\n"
    "悲伤的；伤心；忧愁的。\n"
    "悲伤的；伤心；忧愁的。\n"
    "悲伤的；伤心；忧愁的。\n"
    "悲伤的；伤心；忧愁的。\n"
    "悲伤的；伤心；忧愁的。\n"
    "悲伤的；伤心；忧愁的。\n"
    "悲伤的；伤心；忧愁的。\n"
    "悲伤的；伤心；忧愁的。\n"
    "悲伤的；伤心；忧愁的。\n"
    "悲伤的；伤心；忧愁的。\n"
    "悲伤的；伤心；忧愁的。\n"
    "悲伤的；伤心；忧愁的。\n"
    "悲伤的；伤心；忧愁的。\n"
    "悲伤的；伤心；忧愁的。\n"
    "悲伤的；伤心；忧愁的。\n"
}
,{L"sad for what", 1, 0, "sad because of rain"}
,{L"Values，何为价值观", 2, 0, 
"倡导富强、民主、文明、和谐,\n"
"倡导自由、平等、公正、法治,\n"
"倡导爱国、敬业、诚信、友善\n"
"倡导富强、民主、文明、和谐,\n"
"倡导自由、平等、公正、法治,\n"
"倡导爱国、敬业、诚信、友善\n"
"倡导富强、民主、文明、和谐,\n"
"倡导自由、平等、公正、法治,\n"
"倡导爱国、敬业、诚信、友善\n"
"倡导富强、民主、文明、和谐,\n"
"倡导自由、平等、公正、法治,\n"
"倡导爱国、敬业、诚信、友善\n"
"倡导富强、民主、文明、和谐,\n"
"倡导自由、平等、公正、法治,\n"
"倡导爱国、敬业、诚信、友善\n"
"倡导富强、民主、文明、和谐,\n"
"倡导自由、平等、公正、法治,\n"
"倡导爱国、敬业、诚信、友善\n"
"倡导富强、民主、文明、和谐,\n"
"倡导自由、平等、公正、法治,\n"
"倡导爱国、敬业、诚信、友善\n"
"倡导富强、民主、文明、和谐,\n"
"倡导自由、平等、公正、法治,\n"
"倡导爱国、敬业、诚信、友善\n"
"倡导富强、民主、文明、和谐,\n"
"倡导自由、平等、公正、法治,\n"
"倡导爱国、敬业、诚信、友善\n"
"倡导富强、民主、文明、和谐,\n"
"倡导自由、平等、公正、法治,\n"
"倡导爱国、敬业、诚信、友善\n"
"倡导富强、民主、文明、和谐,\n"
"倡导自由、平等、公正、法治,\n"
"倡导爱国、敬业、诚信、友善\n"
"倡导富强、民主、文明、和谐,\n"
"倡导自由、平等、公正、法治,\n"
"倡导爱国、敬业、诚信、友善\n"
"倡导富强、民主、文明、和谐,\n"
"倡导自由、平等、公正、法治,\n"
"倡导爱国、敬业、诚信、友善\n"
"倡导富强、民主、文明、和谐,\n"
"倡导自由、平等、公正、法治,\n"
"倡导爱国、敬业、诚信、友善\n"
"倡导富强、民主、文明、和谐,\n"
"倡导自由、平等、公正、法治,\n"
"倡导爱国、敬业、诚信、友善\n"
"倡导富强、民主、文明、和谐,\n"
"倡导自由、平等、公正、法治,\n"
"倡导爱国、敬业、诚信、友善\n"
"倡导富强、民主、文明、和谐,\n"
"倡导自由、平等、公正、法治,\n"
"倡导爱国、敬业、诚信、友善\n"
"倡导富强、民主、文明、和谐,\n"
"倡导自由、平等、公正、法治,\n"
"倡导爱国、敬业、诚信、友善\n"
"倡导富强、民主、文明、和谐,\n"
"倡导自由、平等、公正、法治,\n"
"倡导爱国、敬业、诚信、友善\n"
"倡导富强、民主、文明、和谐,\n"
"倡导自由、平等、公正、法治,\n"
"倡导爱国、敬业、诚信、友善\n"
}
,{L"成功秘诀.pdf", 3, 0, 
"苦海无涯。\n"
"苦海无涯。\n"
"苦海无涯。\n"
"苦海无涯。\n"
"苦海无涯。\n"
"苦海无涯。\n"
"苦海无涯。\n"
"苦海无涯。\n"
"苦海无涯。\n"
"苦海无涯。\n"
"苦海无涯。\n"
"苦海无涯。\n"
"苦海无涯。\n"
"苦海无涯。\n"
"苦海无涯。\n"
"苦海无涯。\n"
"苦海无涯。\n"
"苦海无涯。\n"
"苦海无涯。\n"
"苦海无涯。\n"
"苦海无涯。\n"
"苦海无涯。\n"
"苦海无涯。\n"
"苦海无涯。\n"
"苦海无涯。\n"
"苦海无涯。\n"
"苦海无涯。\n"
"苦海无涯。\n"
}
,{L"happy", 0, 0, "哈哈。\n"}
,{L"happy", 0, 0, "哈哈。\n"}
,{L"SecretToHappiness.pdf", 4, 0, "请输入财富密码。\n"}
,{L"MasterCPP.pdf", 4, 0, "[](){}。\n"}
,{L"hello.lua", 0, 0, 
"print (\"Hello, World!\")\n"
"\n"
"\n"
"function showStripAndPlay()\n"
"	--if editor.SelectionStart == editor.SelectionEnd then\n"
"	--	scite.StripShow(\"\")\n"
"	--else\n"
"		scite.StripShow(\"!'Explanation:'{}(&Search)\\n'Name:'[Name](OK)(Cancel)\")\n"
"		scite.StripSetList(1, \"Apple\\nBanana\\nLemon\\nOrange\\nPear\\nKiwi\")\n"
"		scite.StripSet(1, \"<choose a fruit>\")\n"
"		scite.StripSet(4, \"A longer name\")\n"
"	--end\n"
"end\n"
"\n"
"function OnStrip(control, change)\n"
"	local changeNames = { 'unknown', 'clicked', 'change', 'focusIn', 'focusOut' }\n"
"	print(\"OnStrip: \" .. control .. \" -> \" .. changeNames[change + 1])\n"
"	if control == 2 and change == 1 then -- Click in the combo box\n"
"		local search = scite.StripValue(1)\n"
"		print(\"Searching for \" .. search)\n"
"	elseif control == 5 and change == 1 then -- Click on OK\n"
"		print(\"Control states: list=\" .. scite.StripValue(1) .. \", text=\" .. scite.StripValue(4))\n"
"		scite.StripShow(\"\") -- Hide the dialog\n"
"		elseif control == 6 and change == 1 then -- Click on Cancel\n"
"		scite.StripShow(\"\") -- Just hide the dialog\n"
"	end\n"
"end\n"
"\n"
"showStripAndPlay()\n"}
,{L"happy", 0, 0, "哈哈。\n"}
,{L"Your photo.png", 5, 0, "🐕\n"}
,{L"happy", 0, 0, "哈哈。\n"}
,{L"happy", 0, 0, "哈哈。\n"}
};